# -*- coding: utf-8 -*-
# ──────────────────────────────────────────────────────────────────────────────
# Section 151 (2026-10-04) — CSV import keeps EVERY row (40 → 40, not 24)
#
# Root cause: _qxz_store_rows tags rows as source="gen_<mode>", so CSV rows
# became "gen_csv" and were treated as AI-generated by the buffer_add chain:
#   • Section 80 rejected rows whose options look identical once symbols are
#     stripped (math options like "1" vs "−1", "√3" vs "3") and re-shuffled
#     the correct answer slot of the rest.
#   • Section 81's language lock could drop rows in the "wrong" language.
# CSV rows are the user's own finished quizzes, so they must be stored
# verbatim. This overlay re-tags CSV payloads as "csv_import" at the outermost
# buffer_add, and makes the store report the REAL number added.
# Generation, OCR, harvest and all other flows are unchanged.
# ──────────────────────────────────────────────────────────────────────────────

import contextlib as _cx151

_qx151_prev_buffer_add = globals().get("buffer_add")

if callable(_qx151_prev_buffer_add):
    def buffer_add(user_id, payload):  # noqa: F811
        data = payload
        if isinstance(payload, dict):
            source = str(payload.get("source") or "").lower()
            if source == "gen_csv":
                data = dict(payload)
                data["source"] = "csv_import"
        return _qx151_prev_buffer_add(user_id, data)

    globals()["buffer_add"] = buffer_add


_qx151_prev_store = globals().get("_qxz_store_rows")

if callable(_qx151_prev_store):
    def _qxz_store_rows(uid, rows, mode="std"):  # noqa: F811
        if str(mode or "").lower() != "csv":
            return _qx151_prev_store(uid, rows, mode)
        before = None
        with _cx151.suppress(Exception):
            before = int(buffer_count(uid) or 0)  # type: ignore[name-defined]
        added, dup = _qx151_prev_store(uid, rows, mode)
        if before is not None:
            with _cx151.suppress(Exception):
                real = max(0, int(buffer_count(uid) or 0) - before)  # type: ignore[name-defined]
                if real != int(added or 0):
                    with _cx151.suppress(Exception):
                        logger.warning("[S151] csv store reported %s but buffer grew %s", added, real)  # type: ignore[name-defined]
                added = real
        return added, dup

    globals()["_qxz_store_rows"] = _qxz_store_rows

with _cx151.suppress(Exception):
    logger.info("[S151] CSV import stores every row verbatim (no gen-only gates)")  # type: ignore[name-defined]
